export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES';
export const LOAD_ARTICLE = 'LOAD_ARTICLE';

export const ADD_TITLE_FILTERS = 'ADD_TITLE_FILTERS';

export const ADD_DATE_FILTERS = 'ADD_DATE_FILTERS';

export const LOAD_ARTICLE_COMMENTS = 'LOAD_ARTICLE_COMMENTS';
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';

export const START = '_START';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';